### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by soumataniguchi** [soumataniguchi/chat-space#4]
#IPアドレス
18.180.139.100

**Comment by chiii220** [comment]
谷口さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①グループ名、メッセージ表記にある下線を消しましょう（図の①）

②ログアウトボタンとグループ作成ボタンの位置が左に寄っているので右へ寄せましょう。（図の②）

③ユーザー名の横に日付表示ができるようにしましょう。（図の③）
現在
[![Image from Gyazo](https://i.gyazo.com/cf80b67efab9f5f469c2b3447cf52173.png)](https://gyazo.com/cf80b67efab9f5f469c2b3447cf52173)

模範
[![Image from Gyazo](https://i.gyazo.com/8f834c8687e2eb0dff0fea3cc4925277.png)](https://gyazo.com/8f834c8687e2eb0dff0fea3cc4925277)

④インクリメンタルサーチができない
[![Image from Gyazo](https://i.gyazo.com/1e5fb866544c4b926e27e779ab4101ed.gif)](https://gyazo.com/1e5fb866544c4b926e27e779ab4101ed)

⑤自動更新ができない
[![Image from Gyazo](https://i.gyazo.com/8f834c8687e2eb0dff0fea3cc4925277.png)](https://gyazo.com/8f834c8687e2eb0dff0fea3cc4925277)

⑥メッセージにカーソルを置くと、青い枠がずれて表示される
[![Image from Gyazo](https://i.gyazo.com/48580032d49115e37ed314c89ec2312e.png)](https://gyazo.com/48580032d49115e37ed314c89ec2312e)

⑦ログイン画面の英語表記を日本語表記にしましょう
[![Image from Gyazo](https://i.gyazo.com/24d59cf87f4611a7904dd472233f118e.png)](https://gyazo.com/24d59cf87f4611a7904dd472233f118e)

※カリキュラムの中にある、模範のchatspaceと仕様書を参考に、修正をお願いします。
[模範のchatpsace]
https://chat-space-sample.herokuapp.com/
[仕様書]
https://tech-master.s3.amazonaws.com/uploads/curriculums//03e925297f3843c603f028b177b4e86b.png

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by soumataniguchi** [comment]
お疲れ様です
ご指摘いただいた点、修正いたしました。

１〜６までは、指摘いただいた通り修正できました。
しかし７番目に関してですが、『英語表記を日本語表記に』とあります。
サンプルを見ると『sign up』のボタンが英語表記でしたので、ビューのみ修正しました

確認よろしくお願いいたします

**Comment by naru6117** [comment]
修正とご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
①インクリメンタルサーチができない

②サイドバーに表示される最新メッセージの文字サイズが規定よりも小さい

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by soumataniguchi** [comment]
提出遅くなりました
指摘いただいた点、修正いたいました
確認お願いいたします

#IPアドレス
18.180.139.100

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
